{% set version = "1.1-8.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lokern
  version: {{ version|replace("-", "_") }}

source:
  fn: lokern_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/lokern_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/lokern/lokern_{{ version }}.tar.gz
  sha256: 238b99fb3e68d570726de982515739809cd1d66255c0f695be0fc87b41782bfd

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-sfsmisc >=1.0_12

  run:
    - r-base
    - r-sfsmisc >=1.0_12

test:
  commands:
    - $R -e "library('lokern')"  # [not win]
    - "\"%R%\" -e \"library('lokern')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=lokern
  license: GPL (>= 2)
  summary: Kernel regression smoothing with adaptive local or global plug-in bandwidth selection.
  license_family: GPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - sebastian-luna-valero
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
