{% set version = "1.1-12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lokern
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lokern_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lokern/lokern_{{ version }}.tar.gz
  sha256: 6c71ef9fff25078010b2bba34f418f1d62402de2a54f7563d911db5bf0acd577

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("c") }}                # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-sfsmisc >=1.0_12
  run:
    - r-base
    - r-sfsmisc >=1.0_12

test:
  commands:
    - $R -e "library('lokern')"           # [not win]
    - "\"%R%\" -e \"library('lokern')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=lokern
  license: GPL-2.0-or-later
  summary: Kernel regression smoothing with adaptive local or global plug-in bandwidth selection.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - sebastian-luna-valero

# Package: lokern
# Version: 1.1-9
# Date: 2021-04-09
# Title: Kernel Regression Smoothing with Local or Global Plug-in Bandwidth
# Author: Eva Herrmann <eherrmann@mathematik.tu-darmstadt.de> (F77 & S original); Packaged for R and enhanced by Martin Maechler
# Maintainer: Martin Maechler <maechler@stat.math.ethz.ch>
# Imports: grDevices, graphics, stats, utils, sfsmisc (>= 1.0-12)
# Description: Kernel regression smoothing with adaptive local or global plug-in bandwidth selection.
# BuildResaveData: no
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2021-04-09 15:50:52 UTC; maechler
# Repository: CRAN
# Date/Publication: 2021-04-13 22:00:08 UTC
