travis:
  secure:
    BINSTAR_TOKEN: vdJ7bNJPzKzdQ14Y2Gflxj+H0ocm6vhqqnG2OCigt2vfJ7s+Q4tDlT7OuW8hHxqjCEx9+B0wQcevdn+pUGxCYYIUyGJ/OcAdSnl9TfCgMrP2P3Z45CN3PV6uDApYlviteu4HScy992DzcDNgSzffzHfJUglUjiLPOZ8HdTeasEVuIrYTNKHeWd/yoaF2B1dGcaj+5wIgWY3NX8SHwlWh+nkGreYuZesdZkZ/mvPoXUZvTCzgdbwlDqR4OVEvEc2MZUyKhBCaxVn4nqh0sX8BvdlEFcMmrV9nduYnpkdabfSYoTZXBwzeLCFlTyt4vmjmNUOZvDRy3B2wdyClxhpUdVynFEZOgPU6clJWbuP0DCE+FJPtYXVtFlrFC0pw68kk45kbw5qhAgGWMi674s6sELSvSlcKPyPEt8LNYeVv42DDB8O7cP1bzUKTTXgGpVirMZWTspyR4pgiN1ldjaHJxvuhiJW+s6fh2GlhB4qE6bxPhHzglsOi35nzUgsGiTaEZQZ9f+NJdHsuzvnkLuJ2LuADTRW2ZXTpBRCArRrHCUYMvQGQ1QbYrLCYwW6TFYPw9raVqo7Hz9qDHhZk5FLGjHE9GqdB60c0ffpNhTyFOb0vzit/HZuederBWSXfQ+HD94W7S7aMjTA3D2BE/QEYb91TOiQ1//vlJxJdZLexT4s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
