travis:
  secure:
    BINSTAR_TOKEN: svUvhiV6La+VgWlqCuNYlApXpa79+yvQ11X8MVtFt9r67F7YPPS3vO/c62h2bHkWUaFcElVgCIiWzKKRuT1f9e0jwcTFEMlEznqBTGFRySlz0lXSAYaF7Srz5+xrHyVRpfuRWlQw/qeAKvgN5zinuGdQ5vkezONJDSrEvC3iJowwkgep/+YVVlZ7rVmTl2spa+j6zgTz+2whiYVdR3y3RGZ5luF1tKvX/21oNUPkw7qZhx8vP+RJJaH39zRh/EWfNjBGcP7c1KZgRgD/bFd3LbrAePdip1t7nPyurq5hk6s6ADObl3ZNouOSFtDDGcS3YNHBdwftlKwQguKdPX3EtohgkE44PF0tZmR5VABcaYoU1ZVczuYcVg8N9GE7StGLmeEPp6+9D8GN68n2u23wVgvj7KZfnNLsO5jJijPeWCvS6clVbMkvPQJZigpsZGC2gvi5RMbeSo85Uw3sXyOn85UF+zQR/iQy8imNlqzMhwhyBCbAesBR/Z/nTw2vpcA/bww9/m5vMW82t0ZZc3/B/KuXB+/zENSc8NMGiW1Gudrj3eakjfLmCdsiP5K1MpoOMUcuBJ9t3LuRDmKGZVjaClhrZOYviZqOq8jE/9hcOsdHKZYlIAuty/3ccnZD0Z2yTx53jwTL9dZBO/JFA2steGvIsG+NUlPJa3mS//qAAeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
